services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: ezshop-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - ezshop-net

networks:
  ezshop-net:
    name: ezshop-net
    driver: bridge
