services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: ezshop-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ezshop.local
      PGADMIN_DEFAULT_PASSWORD: Admin@123456
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - ezshop-net

networks:
  ezshop-net:
    name: ezshop-net
    driver: bridge
